### ISSUE TITLE
[Request] Rainbow roles

### ISSUE THREAD

**Issue by Roki100** [GamingGeek/Fire#18]
**Is your feature request related to a problem? Please describe.**
yes, i miss rainbow roles feature

**Describe the solution you'd like**
working and customizable rainbow roles

**Describe alternatives you've considered**
working rainbow roles

**Additional context**
makes roles rainbow

**Comment by GamingGeek** [comment]
api aboose
![reeeeee](https://user-images.githubusercontent.com/29981918/77239644-ff60e380-6bd4-11ea-823e-59e882421c1c.png)
